apiVersion: humanitec.io/v1alpha1
kind: SecretStore
metadata:
  name: ${SECRET_STORE_ID}
  namespace: humanitec-operator
  labels:
    app.humanitec.io/default-store: "true"
spec:
  awssm:
    region: ${SECRETS_MANAGER_REGION}
    auth: {}
